version: '3.7'
services:
  solr-poc-backend:
    build: ../
    container_name: solr-poc-backend
    networks:
      - solr-net
    ports:
      - "8889:8888"
# curl -i -X POST -H "Content-Type: multipart/form-data" -F "file=@/home/himanshu/test.csv" http://localhost:8888/upload

  solr-1:
    image: solr:latest
    container_name: solr-1
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zoo-1:2181,zoo-2:2181,zoo-3:2181
    networks:
      - solr-net
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3

  solr-2:
    image: solr:latest
    container_name: solr-2
    ports:
      - "8982:8983"
    environment:
      - ZK_HOST=zoo-1:2181,zoo-2:2181,zoo-3:2181
    networks:
      - solr-net
    depends_on:
      - zoo-1
      - zoo-2
      - zoo-3

  zoo-1:
    image: zookeeper:latest
    container_name: zoo-1
    restart: always
    hostname: zoo-1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr-net

  zoo-2:
    image: zookeeper:latest
    container_name: zoo-2
    restart: always
    hostname: zoo-2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr-net

  zoo-3:
    image: zookeeper:latest
    container_name: zoo-3
    restart: always
    hostname: zoo-3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo-1:2888:3888;2181 server.2=zoo-2:2888:3888;2181 server.3=zoo-3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
    networks:
      - solr-net

networks:
  solr-net:
